using Riok.Mapperly.Abstractions;
using ToDoApp.Data.Features.Categories;
using ToDoApp.WebAPI.Features.Tasks.Dtos;
using ToDoApp.WebAPI.Features.Tasks_Categories;

namespace ToDoApp.WebAPI.Features.Categories.Dtos;

[Mapper]
[UseStaticMapper(typeof(TaskMapper))]
[UseStaticMapper(typeof(Tasks_Categories_Mapper))]
public static partial class CategoryMapper
{
    public static partial CategoryDto ToDto(this CategoryEntity entity); //Source-Generated by Mapperly
    public static partial IEnumerable<CategoryDto> ToDtos(this IEnumerable<CategoryEntity> entities); //Source-Generated by Mapperly

    [MapPropertyFromSource(nameof(CategoryEntity.Tasks))]
    public static partial CategoryEntity ToEntity(this CategoryDto dto); //Source-Generated by Mapperly
    public static partial IEnumerable<CategoryEntity> ToEntities(this IEnumerable<CategoryDto> dtos); //Source-Generated by Mapperly
    public static partial void MapToDto(this CategoryEntity entity, CategoryDto dto); //Source-Generated by Mapperly
    public static partial void MapToDto(this CategoryDto source, CategoryDto destination); //Source-Generated by Mapperly

    [MapPropertyFromSource(nameof(CategoryEntity.Tasks))]
    public static partial void MapToEntity(this CategoryDto dto, CategoryEntity entity); //Source-Generated by Mapperly
    public static partial void MapToEntity(this CategoryEntity source, CategoryEntity destination); //Source-Generated by Mapperly
    public static partial IQueryable<CategoryDto> ProjectToDtos(this IQueryable<CategoryEntity> query); //Source-Generated by Mapperly
}