using Riok.Mapperly.Abstractions;
using ToDoApp.Data.Features.Categories;
using ToDoApp.WebAPI.Features.Tasks.Dtos;
using ToDoApp.Data.Features.Tasks_Categories;

namespace ToDoApp.WebAPI.Features.Categories.Dtos;

[Mapper]
[UseStaticMapper(typeof(TaskMapper))]
public static partial class CategoryMapper
{
    private static Guid GetCategoryId(Task_Category_JoinEntity entity)
    {
        return entity.CategoryId;
    }
    private static List<Task_Category_JoinEntity> ToJoinEntities(CategoryDto dto)
    {
        return dto.Tasks.Select(taskId => new Task_Category_JoinEntity()
        {
            TaskId = taskId,
            CategoryId = dto.Id
        }).ToList();
    }

    [MapperIgnoreSource(nameof(CategoryEntity.User))]
    [MapperIgnoreSource(nameof(CategoryEntity.UserId))]
    public static partial CategoryDto ToDto(this CategoryEntity entity); //Source-Generated by Mapperly
    public static partial IEnumerable<CategoryDto> ToDtos(this IEnumerable<CategoryEntity> entities); //Source-Generated by Mapperly

    [MapPropertyFromSource(nameof(CategoryEntity.Tasks))]
    [MapperIgnoreTarget(nameof(CategoryEntity.User))]
    [MapperIgnoreTarget(nameof(CategoryEntity.UserId))]
    public static partial CategoryEntity ToEntity(this CategoryDto dto); //Source-Generated by Mapperly
    public static partial IEnumerable<CategoryEntity> ToEntities(this IEnumerable<CategoryDto> dtos); //Source-Generated by Mapperly

    [MapperIgnoreSource(nameof(CategoryEntity.User))]
    [MapperIgnoreSource(nameof(CategoryEntity.UserId))]
    public static partial void MapToDto(this CategoryEntity entity, CategoryDto dto); //Source-Generated by Mapperly
    public static partial void MapToDto(this CategoryDto source, CategoryDto destination); //Source-Generated by Mapperly

    [MapPropertyFromSource(nameof(CategoryEntity.Tasks))]
    [MapperIgnoreTarget(nameof(CategoryEntity.User))]
    [MapperIgnoreTarget(nameof(CategoryEntity.UserId))]
    public static partial void MapToEntity(this CategoryDto dto, CategoryEntity entity); //Source-Generated by Mapperly
    public static partial void MapToEntity(this CategoryEntity source, CategoryEntity destination); //Source-Generated by Mapperly
    public static partial IQueryable<CategoryDto> ProjectToDtos(this IQueryable<CategoryEntity> query); //Source-Generated by Mapperly
}