<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d2086db5-d92c-48fc-805f-ea4ac59c03f5</UserSecretsId>
	<InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.AspNetCore.OpenApi.Generated</InterceptorsNamespaces>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore.Microsoft" Version="2.16.17" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
	<PackageReference Include="ErrorOr" Version="2.1.1" />
	<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
	<PackageReference Include="Mediator.Abstractions" Version="3.0.2" />
	<PackageReference Include="Mediator.SourceGenerator" Version="3.0.2">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Riok.Mapperly" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ToDoApp.Data\ToDoApp.Data.csproj" />
    <ProjectReference Include="..\ToDoApp.ServiceDefaults\ToDoApp.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
