using Riok.Mapperly.Abstractions;
using ToDoApp.Data.Features.Tasks;
using ToDoApp.Data.Features.Tasks_Categories;
using ToDoApp.WebAPI.Features.Categories.Dtos;

namespace ToDoApp.WebAPI.Features.Tasks.Dtos;

[Mapper]
[UseStaticMapper(typeof(CategoryMapper))]
public static partial class TaskMapper
{
    private static Guid GetTaskId(Task_Category_JoinEntity entity)
    {
        return entity.TaskId;
    }
    private static List<Task_Category_JoinEntity> ToJoinEntities(TaskDto dto)
    {
        return dto.Categories.Select(categoryId => new Task_Category_JoinEntity()
        {
            TaskId = dto.Id,
            CategoryId = categoryId,
        }).ToList();
    }

    public static partial TaskDto ToDto(this TaskEntity entity); //Source-Generated by Mapperly
    public static partial IEnumerable<TaskDto> ToDtos(this IEnumerable<TaskEntity> entities); //Source-Generated by Mapperly
    
    [MapPropertyFromSource(nameof(TaskEntity.Categories))]
    public static partial TaskEntity ToEntity(this TaskDto dto); //Source-Generated by Mapperly
    public static partial IEnumerable<TaskEntity> ToEntities(this IEnumerable<TaskDto> dtos); //Source-Generated by Mapperly
    public static partial void MapToDto(this TaskDto source, TaskDto destination); //Source-Generated by Mapperly
    public static partial void MapToDto(this TaskEntity entity, TaskDto dto); //Source-Generated by Mapperly

    [MapPropertyFromSource(nameof(TaskEntity.Categories))]
    public static partial void MapToEntity(this TaskDto dto, TaskEntity entity); //Source-Generated by Mapperly
    public static partial void MapToEntity(this TaskEntity source, TaskEntity destination); //Source-Generated by Mapperly
    public static partial IQueryable<TaskDto> ProjectToDtos(this IQueryable<TaskEntity> query); //Source-Generated by Mapperly
}